T2D-242 Compliance Testing
EBIvariation/amp-t2d-kb-test pull request #1
Opened 2018-09-25 09:41 UTC by selvaebi

2018-10-01 09:05 UTC, selvaebi commented
https://www.ebi.ac.uk/ega/ampt2d/jenkins/job/ampt2d-kb-test/view/change-requests/job/PR-1/11/cucumber-html-reports/overview-features.html

2018-10-01 15:01 UTC, Zhicheng-Liu requested changes
Looks good. But how do can we test multiple nodes with different baseUrl/apiVersion and datasets?

2018-10-01 15:01 UTC, Zhicheng-Liu commented on pom.xml
> +    <groupId>uk.uk.ac.uk.ac.ebi.uk.ac.ebi.ampt2d</groupId>
Fix the `groupId` to be consistent with other projects please.

2018-10-01 15:03 UTC, selvaebi commented on pom.xml
> +    <groupId>uk.uk.ac.uk.ac.ebi.uk.ac.ebi.ampt2d</groupId>
ah my bad , will fix it

2018-10-01 15:07 UTC, selvaebi commented
I haven't implemented comparing nodes. This is just part one - checking for consistency in our kb , once broad node is up with test dataset , we can implement them.

2018-10-01 15:14 UTC, Zhicheng-Liu approved these changes

2018-10-08 15:43 UTC, iyangar commented on pom.xml
> +
Can we have ```<parent>```

2018-10-08 15:43 UTC, iyangar commented on src/test/resources/features/getData.feature
> +
Few extra blank lines

2018-10-09 09:52 UTC, selvaebi commented on pom.xml
> +
i think we dont have modules . is that mandatory to have parent.

2018-10-09 10:34 UTC, iyangar commented on pom.xml
> +
If there are no modules its not mandatory. Optional if you are going to have modules in future

2018-10-09 10:34 UTC, iyangar approved these changes

2018-10-11 13:20 UTC, cyenyxe requested changes

2018-10-11 13:20 UTC, cyenyxe commented on Jenkinsfile
> +  post{
Missing whitespace.

2018-10-11 13:20 UTC, cyenyxe commented on pom.xml
> +            <version>1.5.10.RELEASE</version>
Given this is a completely new development that doesn't depend in any libraries, we could use Spring Boot 2.

2018-10-11 13:20 UTC, cyenyxe commented on src/test/java/uk/ac/ebi/ampt2d/configuration/KnowledgeBaseApiConfiguration.java
> +        return new KnowledgeBaseApi();
Is it worth creating a new class instead of using just 2 properties directly inside this one?

2018-10-11 13:20 UTC, cyenyxe commented on src/test/java/uk/ac/ebi/ampt2d/step/definitions/StepDefinitions.java
> +    @Given("^I'm using the production API environment$")
This won't be true if the URL set is the staging one. Why not just saying 'given a configured API environment'?

2018-10-11 13:20 UTC, cyenyxe commented on src/test/java/uk/ac/ebi/ampt2d/configuration/KnowledgeBaseApiConfiguration.java
> +    @ConfigurationProperties(prefix = "kb.prod")
Why `prod`? Tests are supposed to be runnable in any environment, not just a production instance.

2018-10-11 13:20 UTC, cyenyxe commented on src/test/java/uk/ac/ebi/ampt2d/step/definitions/StepDefinitions.java
> +    @When("^Hit Url \"([^\"]*)\"$")
`URL` instead of `Url`

2018-10-11 13:20 UTC, cyenyxe commented on src/test/java/uk/ac/ebi/ampt2d/step/definitions/StepDefinitions.java
> +    @Then("^Response returns api version$")
`API` instead of `api`

2018-10-11 13:20 UTC, cyenyxe commented on src/test/java/uk/ac/ebi/ampt2d/step/definitions/StepDefinitions.java
> +    @Then("^Response returns valid json in response same as expected in (.*?)$")
Maybe `Response is the expected JSON (.*?)` sounds a bit more clear?

2018-10-11 13:20 UTC, cyenyxe commented on src/test/java/uk/ac/ebi/ampt2d/step/definitions/StepDefinitions.java
> +    @When("^Hit Url \"([^\"]*)\" with ([^ ]*) with ([^ ]*) and unknown phenotype\\(([^)]*)\\)$")
> Hit Url "/getData" with getDataDatasetsInput with AMPLOAD_36_mdv1 and unknown phenotype(ADIPONECTIN)

I don't understand what this means, is this trying to retrieve the phenotypes in a dataset, check whether a phenotype exists in it...?

Acceptance tests are supposed to describe cases in a way that is related to the technical details. I suppose `getDataDatasetsInput` is one of the test files; that is definitely a very low-level technical detail so this needs to be rephrased.

2018-10-11 13:20 UTC, cyenyxe commented on src/test/java/uk/ac/ebi/ampt2d/step/definitions/StepDefinitions.java
> +public class StepDefinitions {
None of these tests check the HTTP status codes in the response.

2018-10-12 10:47 UTC, selvaebi commented on src/test/java/uk/ac/ebi/ampt2d/configuration/KnowledgeBaseApiConfiguration.java
> +        return new KnowledgeBaseApi();
will be adding new properties if we gonna eest against brod or oxford nodes.

2018-10-12 10:53 UTC, selvaebi commented on src/test/java/uk/ac/ebi/ampt2d/step/definitions/StepDefinitions.java
> +public class StepDefinitions {
ya for all the endpoints they just return same 200 status code for ok / validation error or parsing error , there is flag is_error true/false which am checking for all requests.

2018-10-16 10:15 UTC, cyenyxe commented on src/test/java/uk/ac/ebi/ampt2d/step/definitions/StepDefinitions.java
> +public class StepDefinitions {
I still think it is important to check the status codes. The way they are handling errors is not standard at all, and at any point errors could be flagged using HTTP codes and/or `is_error`.

2018-10-16 10:17 UTC, cyenyxe requested changes

2018-10-16 10:17 UTC, cyenyxe commented on src/test/java/uk/ac/ebi/ampt2d/step/definitions/StepDefinitions.java
> +    public void hitGetDataURLWithUnknownPhenotype(String path, String datasetName, String phenotype, String jsonFile)
This method name doesn't seem correct anymore.

2018-10-16 10:17 UTC, cyenyxe commented on src/test/java/uk/ac/ebi/ampt2d/step/definitions/StepDefinitions.java
> +public class StepDefinitions {
I still think it is important to check the status codes. The way they are handling errors is not standard at all, and at any point errors could be flagged using HTTP codes and/or `is_error`.

2018-10-17 10:16 UTC, cyenyxe approved these changes

2018-10-17 10:17 UTC, merged